{% set version = "2017_20170412" %}

package:
  name: tbb
  version: {{ version }}

source:
  fn: tbb{{ version }}oss_src.tgz
  url: https://github.com/01org/tbb/archive/2017_U6.tar.gz
  sha256: 1f7df7af6045179a45eba9b5dfde74d185ee7f573328f103c137696f81e4ae5a

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]
  skip: true  # [win and py36]

requirements:
  build:
    - toolchain
    - python  # [win]
    - cmake  # [win]

test:
  requires:
    - python {{ os.environ.get('PY_VER', '') + '*' }}  # [win]

  commands:
    - test -f ${PREFIX}/include/tbb/tbb.h  # [unix]
    - test -f ${PREFIX}/lib/libtbb.so  # [linux]
    - test -f ${PREFIX}/lib/libtbb.dylib  # [osx]
    - if not exist %PREFIX%\\Library\\include\\tbb\\tbb.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\tbb_debug.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\tbb_debug.dll exit 1  # [win]

about:
  home: http://www.threadingbuildingblocks.org
  license: Apache 2.0
  license_file: LICENSE
  summary: High level abstract threading library

extra:
  recipe-maintainers:
    - jschueller
