{% set version = "2017_20160722" %}
{% set flat_version=version.replace(".", "") %}

package:
  name: tbb
  version: {{ version }}

source:
  fn: tbb{{ flat_version }}oss_src.tgz
  url: https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb{{ flat_version }}oss_src.tgz
  sha256: fd5fb4c4e0bf6025eb45d12bd7a474821c8e1b45dbf39fe50a256aa4c7ae190d

build:
  number: 0
  features:
    - vc9    # [win and py27]
    - vc10   # [win and py34]
    - vc14   # [win and py35]

requirements:
  build:
    - toolchain
    - python  # [win]
    - cmake   # [win]

test:
  requires:
    - python 2.7.*  # [win and py27]
    - python 3.4.*  # [win and py34]
    - python 3.5.*  # [win and py35]

  commands:
    - test -f ${PREFIX}/include/tbb/tbb.h  # [unix]
    - test -f ${PREFIX}/lib/libtbb.so  # [linux]
    - test -f ${PREFIX}/lib/libtbb.dylib  # [osx]

about:
  home: http://www.threadingbuildingblocks.org
  license: Apache 2.0
  license_file: LICENSE
  summary: High level abstract threading library

extra:
  recipe-maintainers:
    - jschueller

