{% set version = "2018_20171205" %}

package:
  name: tbb
  version: {{ version }}

source:
  fn: tbb{{ version }}oss_src.tgz
  url: https://github.com/01org/tbb/archive/2018_U2.tar.gz
  sha256: 78bb9bae474736d213342f01fe1a6d00c6939d5c75b367e2e43e7bf29a6d8eca

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]
  skip: true  # [win and py36]

requirements:
  build:
    - toolchain
    - python  # [win]
    - cmake  # [win]

test:
  requires:
    - python {{ os.environ.get('PY_VER', '') + '*' }}  # [win]

  commands:
    - test -f ${PREFIX}/include/tbb/tbb.h  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libtbb${SHLIB_EXT}']"  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'%PREFIX%\Library\bin\tbb.dll']"  # [win]
    - if not exist %PREFIX%\\Library\\include\\tbb\\tbb.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\tbb.lib exit 1  # [win]

about:
  home: http://www.threadingbuildingblocks.org
  license: Apache 2.0
  license_file: LICENSE
  summary: High level abstract threading library

extra:
  recipe-maintainers:
    - jschueller
