{% set version = "2017_20161004" %}

package:
  name: tbb
  version: {{ version }}

source:
  fn: tbb{{ version }}oss_src.tgz
  url: https://www.threadingbuildingblocks.org/sites/default/files/software_releases/source/tbb{{ version }}oss_src.tgz
  sha256: f4ba7a7ed1bcb6c05d47e73624ca2e4580104bc0d3e0a3ccc7b67fa324760cb1

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py35]

requirements:
  build:
    - toolchain
    - python  # [win]
    - cmake  # [win]

test:
  requires:
    - python 2.7.*  # [win and py27]
    - python 3.4.*  # [win and py34]
    - python 3.5.*  # [win and py35]

  commands:
    - test -f ${PREFIX}/include/tbb/tbb.h  # [unix]
    - test -f ${PREFIX}/lib/libtbb.so  # [linux]
    - test -f ${PREFIX}/lib/libtbb.dylib  # [osx]

about:
  home: http://www.threadingbuildingblocks.org
  license: Apache 2.0
  license_file: LICENSE
  summary: High level abstract threading library

extra:
  recipe-maintainers:
    - jschueller

