{% set version = "2018_20170919" %}

package:
  name: tbb
  version: {{ version }}

source:
  fn: tbb{{ version }}oss_src.tgz
  url: https://github.com/01org/tbb/archive/2018_U1.tar.gz
  sha256: c6462217d4ecef2b44fce63cfdf31f9db4f6ff493869899d497a5aef68b05fc5

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc14  # [win and py>=35]
  skip: true  # [win and py36]

requirements:
  build:
    - toolchain
    - python  # [win]
    - cmake  # [win]

test:
  requires:
    - python {{ os.environ.get('PY_VER', '') + '*' }}  # [win]

  commands:
    - test -f ${PREFIX}/include/tbb/tbb.h  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libtbb${SHLIB_EXT}']"  # [unix]
    - python -c "import ctypes; ctypes.cdll[r'%PREFIX%\Library\bin\tbb.dll']"  # [win]
    - if not exist %PREFIX%\\Library\\include\\tbb\\tbb.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\tbb.lib exit 1  # [win]

about:
  home: http://www.threadingbuildingblocks.org
  license: Apache 2.0
  license_file: LICENSE
  summary: High level abstract threading library

extra:
  recipe-maintainers:
    - jschueller
