# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "0ku3cxbBdImgHLEEJDXWLWGu+/LwPYm4//JwDUduk1QjGSA30lWOLhFWtlTbIajZBZgS+DSLWC8w7JLb+KM4ygCrScHJ2+4TvMdhsxfRZDsXmZ41fhdFl/si+0LnxIWR3+aiXJAy9Sa1ZrU2rlVWzy0M/Tbd4YcPfZ4yUFLnaB3+N8uQvSW5MNz9R0jrdy4cGDxl/H8rCDIzf4Zp+oDmWwt4Bj03DaJz4oH6Sr37VcuMF1suywQT/nRhmI2hcwvcEQyXkSSea8k4hLR2d8vtkGuXosaopFOnIbebuHRIngGlpSnYnOaHl8z9yziUOnpvVhGnhGuDKKvjC5Grc5XM+uk2EfB0knT4E+X6Fab7I4qpjzX3OxplGLMoHDHsyhyYfA+1+yc2pxyG0kBEL/2NxQqQKeTegzvyLKcRTLaL6fvFqvJ4ACfBlBqu0MC9IuM+G+kDshF0O0/66M7Lyv2t4ZQk7QJTLbc/fWLcH+1N7+9MEzbo77AtLxFa3UaY7+vtPniPl7qirc/MLNUvcp6q9Evd75Ps12/0QGP1foD7xFpJlA4QTYNlXhsUyosEpLRsyUTUhJegn0ag9Y/yXpyvJ9iUhAduy62iVgjAo6ZAn6C1owkIuCD731XcHWSfjZ9ByrKBjeGF8XiD/cEKwQduCes1lq8lylbTF4AcU9nz3f0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
