travis:
  secure:
    BINSTAR_TOKEN: 0ku3cxbBdImgHLEEJDXWLWGu+/LwPYm4//JwDUduk1QjGSA30lWOLhFWtlTbIajZBZgS+DSLWC8w7JLb+KM4ygCrScHJ2+4TvMdhsxfRZDsXmZ41fhdFl/si+0LnxIWR3+aiXJAy9Sa1ZrU2rlVWzy0M/Tbd4YcPfZ4yUFLnaB3+N8uQvSW5MNz9R0jrdy4cGDxl/H8rCDIzf4Zp+oDmWwt4Bj03DaJz4oH6Sr37VcuMF1suywQT/nRhmI2hcwvcEQyXkSSea8k4hLR2d8vtkGuXosaopFOnIbebuHRIngGlpSnYnOaHl8z9yziUOnpvVhGnhGuDKKvjC5Grc5XM+uk2EfB0knT4E+X6Fab7I4qpjzX3OxplGLMoHDHsyhyYfA+1+yc2pxyG0kBEL/2NxQqQKeTegzvyLKcRTLaL6fvFqvJ4ACfBlBqu0MC9IuM+G+kDshF0O0/66M7Lyv2t4ZQk7QJTLbc/fWLcH+1N7+9MEzbo77AtLxFa3UaY7+vtPniPl7qirc/MLNUvcp6q9Evd75Ps12/0QGP1foD7xFpJlA4QTYNlXhsUyosEpLRsyUTUhJegn0ag9Y/yXpyvJ9iUhAduy62iVgjAo6ZAn6C1owkIuCD731XcHWSfjZ9ByrKBjeGF8XiD/cEKwQduCes1lq8lylbTF4AcU9nz3f0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
